[package]
name = "bchain"
version = "0.1.0"
authors = ["@darkest_ruby <art@drkruby.co.uk>"]
edition = "2018"

[[bin]] 
name = "server"
path = "src/bin/server.rs"

[[bin]] 
name = "client"
path = "src/bin/client.rs"

[[bin]] 
name = "test"
path = "src/bin/test.rs"

[dependencies]
tonic = "0.4"
prost = "0.7"
uuid = { version = "0.8", features = ["serde", "v4"] }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
serde = {version="1", features=["derive"]}
serde_cbor = "0.11"

[build-dependencies]
tonic-build = "0.4"
