[package]
name = "bchain"
version = "0.1.0"
authors = ["darkruby <art@darkruby.co.uk>"]
edition = "2018"

[[bin]] 
name = "wallet"
path = "src/bin/wallet.rs"

[[bin]] 
name = "diesel"
path = "src/bin/diesel.rs"

[dependencies]
libp2p="*"
log="0.4"
bytes="1"
rsa="0.5"
hex="0.4"
rand ="0.8"
base58 = "0.1"
sha2 = "0.9"
dotenv="0.15"
futures = "0.3"
byteorder="1.4"
structopt = "0.3"
env_logger = "0.9"
serde_json = "1.0"
serde = {version="1", features=["derive"]}
tokio = { version = "1", features = ["full"] }
pkcs8={version="0.7", features=["alloc", "pem"]}
uuid = { version = "0.8", features = ["serde", "v4"] }

async-std = {version="1.9.0", features=["attributes"]}
diesel = { version = "1.4.7", features = ["sqlite","chrono", "numeric"] }
diesel_migrations = "*"
chrono = "0.4"
