[package]
name = "bchain"
version = "0.1.0"
authors = ["@darkest_ruby <art@darkruby.co.uk>"]
edition = "2018"

[[bin]] 
name = "server"
path = "src/bin/server.rs"
[[bin]] 
name = "client"
path = "src/bin/client.rs"
[[bin]] 
name = "wallet"
path = "src/bin/wallet.rs"

[dependencies]
log="0.4"
bytes="1"
rsa="0.4"
hex="0.4"
rand ="0.8"
sha2 = "0.9"
dotenv="0.15"
futures = "0.3"
byteorder="1.4"
structopt = "0.3"
env_logger = "0.8"
serde_cbor = "0.11"
serde = {version="1", features=["derive"]}
tokio = { version = "1", features = ["full"] }
pkcs8={version="0.7", features=["alloc", "pem"]}
uuid = { version = "0.8", features = ["serde", "v4"] }

diesel = { version = "1.4.7", features = ["sqlite","chrono", "numeric"] }
diesel_migrations = "*"
chrono = "0.4"
