[package]
name = "bchain"
version = "0.1.0"
authors = ["@darkest_ruby <art@drkruby.co.uk>"]
edition = "2018"

[[bin]] 
name = "server"
path = "src/bin/server.rs"

[[bin]] 
name = "client"
path = "src/bin/client.rs"

[dependencies]
tonic = "0.4"
prost = "0.7"
uuid = "0.8"
tokio = { version = "1.6", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.4"
