[package]
name = "bchain-util"
version = "0.1.0"
edition = "2018"

[dependencies]
num="0.4"
hex="0.4"
sha2 = "0.9"
anyhow="1.0"
byteorder="1.4"
serde = {version="1", features=["derive"]}
async-std = {version="1", features=["attributes", "unstable"]}

