[package]
name = "bchain-util"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = {version="1", features=["attributes", "unstable"]}
bchain-domain = { path = "../chain" }
num="0.4"

[dev-dependencies]
anyhow="1.0"